
services:

  redis:
    image: redis:7-alpine
    container_name: seo_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build: .
    container_name: celery_worker
    working_dir: /app
    command: >
      sh -c "celery -A app.shared.tasks worker
      --loglevel=info
      -Q email,crawler
      --without-gossip
      --without-mingle
      --without-heartbeat"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:vksoft123@host.docker.internal:5432/seo_audit
      - REDIS_URL=redis://redis:6379/0
      - REDIS_BROKER_URL=redis://redis:6379/0
      - REDIS_BACKEND_URL=redis://redis:6379/1
    depends_on:
      - redis
    volumes:
      - .:/app

  worker-audit:
    build: .
    container_name: celery_worker_audit
    working_dir: /app
    command: >
      sh -c "celery -A app.shared.tasks worker
      --loglevel=info
      -Q audit
      --without-gossip
      --without-mingle
      --without-heartbeat"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:vksoft123@host.docker.internal:5432/seo_audit
      - REDIS_URL=redis://redis:6379/0
      - REDIS_BROKER_URL=redis://redis:6379/0
      - REDIS_BACKEND_URL=redis://redis:6379/1
    depends_on:
      - redis
    volumes:
      - .:/app


volumes:
  redis_data:

