from __future__ import annotations

import os

STREAMING_AUDIT_MAX_CONCURRENCY = int(os.getenv("STREAMING_AUDIT_MAX_CONCURRENCY", "5"))
STREAMING_AUDIT_MAX_PAGES = int(os.getenv("STREAMING_AUDIT_MAX_PAGES", "100"))
STREAMING_AUDIT_MAX_DEPTH = int(os.getenv("STREAMING_AUDIT_MAX_DEPTH", "3"))
STREAMING_AUDIT_PAGE_TIMEOUT = float(os.getenv("STREAMING_AUDIT_PAGE_TIMEOUT", "30.0"))
STREAMING_AUDIT_BROWSER_CONCURRENCY = int(os.getenv("STREAMING_AUDIT_BROWSER_CONCURRENCY", "2"))
STREAMING_AUDIT_MAX_RETRIES = int(os.getenv("STREAMING_AUDIT_MAX_RETRIES", "3"))
STREAMING_AUDIT_REDIS_NAMESPACE = "streaming_audit"
