"""initial schema

Revision ID: 07515632cae3
Revises: 
Create Date: 2026-09-24 15:38:16.286138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07515632cae3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('crawl_type', sa.String(length=50), nullable=True),
    sa.Column('max_pages', sa.Integer(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('pages_discovered', sa.Integer(), nullable=False),
    sa.Column('pages_crawled', sa.Integer(), nullable=False),
    sa.Column('pages_skipped', sa.Integer(), nullable=False),
    sa.Column('pages_failed', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('current_page', sa.Integer(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('crawl_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=1024), nullable=True),
    sa.Column('crawl_config_recovered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_jobs_user_id'), 'crawl_jobs', ['user_id'], unique=False)
    op.create_table('crawl_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('parent_page_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('scheme', sa.String(length=10), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.SmallInteger(), nullable=True),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('content_length', sa.BigInteger(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('is_crawled', sa.Boolean(), nullable=False),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('is_redirect', sa.Boolean(), nullable=False),
    sa.Column('is_error', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', 'normalized_url', name='uq_crawl_pages_audit_id_normalized_url')
    )
    op.create_index(op.f('ix_crawl_pages_audit_id'), 'crawl_pages', ['audit_id'], unique=False)
    op.create_index(op.f('ix_crawl_pages_host'), 'crawl_pages', ['host'], unique=False)
    op.create_index(op.f('ix_crawl_pages_parent_page_id'), 'crawl_pages', ['parent_page_id'], unique=False)
    op.create_index(op.f('ix_crawl_pages_url_hash'), 'crawl_pages', ['url_hash'], unique=False)
    op.create_table('crawl_site_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crawl_job_id', sa.UUID(), nullable=False),
    sa.Column('robots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sitemaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('statistics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duplicate_clusters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_site_data_crawl_job_id'), 'crawl_site_data', ['crawl_job_id'], unique=True)
    op.create_table('page_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('crawl_job_id', sa.UUID(), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('normalized_target_url', sa.Text(), nullable=True),
    sa.Column('anchor_text', sa.Text(), nullable=True),
    sa.Column('rel', sa.String(length=100), nullable=True),
    sa.Column('link_type', sa.String(length=50), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.Column('nofollow', sa.Boolean(), nullable=False),
    sa.Column('ugc', sa.Boolean(), nullable=False),
    sa.Column('sponsored', sa.Boolean(), nullable=False),
    sa.Column('is_crawlable', sa.Boolean(), nullable=False),
    sa.Column('target_status_code', sa.Integer(), nullable=True),
    sa.Column('target_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('target_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_links_crawl_job_id'), 'page_links', ['crawl_job_id'], unique=False)
    op.create_index(op.f('ix_page_links_page_id'), 'page_links', ['page_id'], unique=False)
    op.create_table('page_network_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('redirects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('security', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_network_data_page_id'), 'page_network_data', ['page_id'], unique=True)
    op.create_table('page_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('alt', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('loading', sa.String(length=20), nullable=True),
    sa.Column('srcset', sa.Text(), nullable=True),
    sa.Column('sizes', sa.Text(), nullable=True),
    sa.Column('is_lazy', sa.Boolean(), nullable=True),
    sa.Column('is_mixed_content', sa.Boolean(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_resources_page_id'), 'page_resources', ['page_id'], unique=False)
    op.create_table('page_seo_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('title_length', sa.Integer(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_description_length', sa.Integer(), nullable=True),
    sa.Column('canonical', sa.Text(), nullable=True),
    sa.Column('robots_meta', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('charset', sa.String(length=50), nullable=True),
    sa.Column('viewport', sa.Text(), nullable=True),
    sa.Column('favicon', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('page_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('headings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('social', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('indexability', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('accessibility', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_seo_data_page_id'), 'page_seo_data', ['page_id'], unique=True)
    op.create_table('parsed_page_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('page_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('elements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parse_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', 'page_id', name='ix_parsed_page_facts_audit_page')
    )
    op.create_index(op.f('ix_parsed_page_facts_audit_id'), 'parsed_page_facts', ['audit_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan_type', sa.String(length=30), nullable=False),
    sa.Column('billing_interval', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('audit_limit', sa.Integer(), nullable=True),
    sa.Column('fair_usage_enabled', sa.Boolean(), nullable=False),
    sa.Column('report_type', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('robot_check',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('exists', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.SmallInteger(), nullable=True),
    sa.Column('fetch_status', sa.Enum('SUCCESS', 'NOT_FOUND', 'UNREACHABLE', name='fetchstatus'), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('fetched_url', sa.Text(), nullable=True),
    sa.Column('user_agent_groups', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sitemaps_declared', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sitemap_reachability', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('syntax_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blocks_entire_site', sa.Boolean(), nullable=False),
    sa.Column('blocks_assets', sa.Boolean(), nullable=False),
    sa.Column('oversized', sa.Boolean(), nullable=False),
    sa.Column('overall_status', sa.Enum('PASS', 'WARNING', 'FAIL', 'NOT_APPLICABLE', name='overallstatus'), nullable=False),
    sa.Column('severity', sa.Enum('NONE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('check_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robot_check_domain'), 'robot_check', ['domain'], unique=False)
    op.create_index('ix_robot_check_domain_checked', 'robot_check', ['domain', 'created_at'], unique=False)
    op.create_table('rule_evaluation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('score_impact', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('rule_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', 'page_id', 'rule_id', name='uq_rule_results_audit_page_rule')
    )
    op.create_index(op.f('ix_rule_evaluation_results_audit_id'), 'rule_evaluation_results', ['audit_id'], unique=False)
    op.create_table('seo_analysis_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('total_pages_scored', sa.Integer(), nullable=False),
    sa.Column('total_rules_evaluated', sa.Integer(), nullable=False),
    sa.Column('total_passed', sa.Integer(), nullable=False),
    sa.Column('total_failed', sa.Integer(), nullable=False),
    sa.Column('critical_issues', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.Integer(), nullable=False),
    sa.Column('error_pages', sa.Integer(), nullable=False),
    sa.Column('error_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('output_file_path', sa.String(length=1024), nullable=True),
    sa.Column('analysis_status', sa.String(length=20), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_analysis_runs_audit_id'), 'seo_analysis_runs', ['audit_id'], unique=True)
    op.create_table('seo_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('report_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('delivered_to', postgresql.ARRAY(sa.String(length=255)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_reports_audit_id'), 'seo_reports', ['audit_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('crawl_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('max_pages', sa.Integer(), nullable=False),
    sa.Column('concurrency', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('delay_ms', sa.Integer(), nullable=False),
    sa.Column('follow_redirects', sa.Boolean(), nullable=False),
    sa.Column('respect_robots', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['crawl_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_configs_audit_id'), 'crawl_configs', ['audit_id'], unique=False)
    op.create_table('crawl_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=True),
    sa.Column('error_type', sa.Enum('fetch_error', 'crawl_error', 'parse_error', 'timeout', 'connection_error', 'robots_error', 'network_error', name='crawl_error_type_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['crawl_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['crawl_pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_errors_audit_id'), 'crawl_errors', ['audit_id'], unique=False)
    op.create_index(op.f('ix_crawl_errors_page_id'), 'crawl_errors', ['page_id'], unique=False)
    op.create_table('otps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('otp_type', sa.Enum('register_otp', 'forgot_pass_otp', 'reset_pass_otp', name='otp_type_enum'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.Enum('image', 'css', 'javascript', 'font', 'video', 'pdf', 'favicon', name='asset_type_enum'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('status_code', sa.SmallInteger(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['crawl_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_assets_page_id'), 'page_assets', ['page_id'], unique=False)
    op.create_table('page_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('compressed', sa.Boolean(), nullable=False),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['crawl_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_snapshots_page_id'), 'page_snapshots', ['page_id'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=1024), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blacklist_jti'), 'token_blacklist', ['jti'], unique=True)
    
    op.create_table('url_ignore_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_type', sa.String(length=10), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('match_type', sa.String(length=20), nullable=True),
    sa.Column('pattern', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('normalized_url', sa.Text(), nullable=True),
    sa.Column('matched_pattern_id', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['crawl_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_pattern_id'], ['url_ignore_patterns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint("record_type IN ('pattern', 'skip')", name='chk_record_type'),
    sa.CheckConstraint("scope IN ('global', 'performance', 'accessibility', 'bestpractices', 'seo', 'runtime')", name='chk_scope'),
    sa.CheckConstraint("match_type IN ('path', 'prefix', 'extension', 'query_param', 'regex', 'scheme', 'host') OR match_type IS NULL", name='chk_match_type'),
    sa.CheckConstraint("(record_type = 'pattern' AND ((match_type IS NOT NULL AND pattern IS NOT NULL) OR scope IN ('performance', 'accessibility', 'bestpractices', 'seo'))) OR (record_type = 'skip' AND audit_id IS NOT NULL AND url IS NOT NULL)", name='chk_pattern_fields')
    )
    op.create_index('ix_url_ignore_patterns_lookup', 'url_ignore_patterns', ['scope', 'is_active', 'sort_order'], unique=False, postgresql_where="record_type = 'pattern' AND is_active = TRUE")
    op.create_index('ix_url_ignore_patterns_skips_audit', 'url_ignore_patterns', ['audit_id'], unique=False, postgresql_where="record_type = 'skip'")
    op.create_index('ix_url_ignore_patterns_skips_reason', 'url_ignore_patterns', ['audit_id', 'reason'], unique=False, postgresql_where="record_type = 'skip'")
    op.create_index('ix_url_ignore_patterns_skips_matched', 'url_ignore_patterns', ['matched_pattern_id'], unique=False, postgresql_where="record_type = 'skip'")
    op.create_index('ix_url_ignore_patterns_unique', 'url_ignore_patterns', ['scope', 'match_type', 'pattern'], unique=True, postgresql_where="record_type = 'pattern'")
    
    
    op.create_table('lighthouse_page_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('check_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('device', sa.Enum('mobile', 'desktop', name='device'), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', 'skipped', name='pagestatus'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('performance_score', sa.Integer(), nullable=True),
    sa.Column('seo_score', sa.Integer(), nullable=True),
    sa.Column('fcp_ms', sa.Integer(), nullable=True),
    sa.Column('lcp_ms', sa.Integer(), nullable=True),
    sa.Column('tbt_ms', sa.Integer(), nullable=True),
    sa.Column('cls', sa.Float(), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('check_id', 'url', 'device', name='uq_check_url_device')
    )
    op.create_index('ix_lighthouse_check_id', 'lighthouse_page_results', ['check_id'], unique=False)
    op.create_index('ix_lighthouse_domain_created', 'lighthouse_page_results', ['domain', 'created_at'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_jti'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_page_snapshots_page_id'), table_name='page_snapshots')
    op.drop_table('page_snapshots')
    op.drop_index(op.f('ix_page_assets_page_id'), table_name='page_assets')
    op.drop_table('page_assets')
    op.drop_table('otps')
    op.drop_index(op.f('ix_crawl_errors_page_id'), table_name='crawl_errors')
    op.drop_index(op.f('ix_crawl_errors_audit_id'), table_name='crawl_errors')
    op.drop_table('crawl_errors')
    op.drop_index(op.f('ix_crawl_configs_audit_id'), table_name='crawl_configs')
    op.drop_table('crawl_configs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_seo_reports_audit_id'), table_name='seo_reports')
    op.drop_table('seo_reports')
    op.drop_index(op.f('ix_seo_analysis_runs_audit_id'), table_name='seo_analysis_runs')
    op.drop_table('seo_analysis_runs')
    op.drop_index(op.f('ix_rule_evaluation_results_audit_id'), table_name='rule_evaluation_results')
    op.drop_table('rule_evaluation_results')
    op.drop_index('ix_robot_check_domain_checked', table_name='robot_check')
    op.drop_index(op.f('ix_robot_check_domain'), table_name='robot_check')
    op.drop_table('robot_check')
    op.drop_table('plans')
    op.drop_index(op.f('ix_parsed_page_facts_audit_id'), table_name='parsed_page_facts')
    op.drop_table('parsed_page_facts')
    op.drop_index(op.f('ix_page_seo_data_page_id'), table_name='page_seo_data')
    op.drop_table('page_seo_data')
    op.drop_index(op.f('ix_page_resources_page_id'), table_name='page_resources')
    op.drop_table('page_resources')
    op.drop_index(op.f('ix_page_network_data_page_id'), table_name='page_network_data')
    op.drop_table('page_network_data')
    op.drop_index(op.f('ix_page_links_page_id'), table_name='page_links')
    op.drop_index(op.f('ix_page_links_crawl_job_id'), table_name='page_links')
    op.drop_table('page_links')
    op.drop_index(op.f('ix_crawl_site_data_crawl_job_id'), table_name='crawl_site_data')
    op.drop_table('crawl_site_data')
    op.drop_index(op.f('ix_crawl_pages_url_hash'), table_name='crawl_pages')
    op.drop_index(op.f('ix_crawl_pages_parent_page_id'), table_name='crawl_pages')
    op.drop_index(op.f('ix_crawl_pages_host'), table_name='crawl_pages')
    op.drop_index(op.f('ix_crawl_pages_audit_id'), table_name='crawl_pages')
    op.drop_table('crawl_pages')
    op.drop_index(op.f('ix_crawl_jobs_user_id'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    # Reverse: drop url_ignore_patterns before crawl_jobs
    op.drop_index('ix_url_ignore_patterns_unique', table_name='url_ignore_patterns', postgresql_where="record_type = 'pattern'")
    op.drop_index('ix_url_ignore_patterns_skips_matched', table_name='url_ignore_patterns', postgresql_where="record_type = 'skip'")
    op.drop_index('ix_url_ignore_patterns_skips_reason', table_name='url_ignore_patterns', postgresql_where="record_type = 'skip'")
    op.drop_index('ix_url_ignore_patterns_skips_audit', table_name='url_ignore_patterns', postgresql_where="record_type = 'skip'")
    op.drop_index('ix_url_ignore_patterns_lookup', table_name='url_ignore_patterns', postgresql_where="record_type = 'pattern' AND is_active = TRUE")
    op.drop_table('url_ignore_patterns')

    # Reverse: drop lighthouse_page_results
    op.drop_index('ix_lighthouse_domain_created', table_name='lighthouse_page_results')
    op.drop_index('ix_lighthouse_check_id', table_name='lighthouse_page_results')
    op.drop_table('lighthouse_page_results')
    # ### end Alembic commands ###
