"""time stamp fixes

Revision ID: a046fe9654e8
Revises: f3a4b5c6d7e8
Create Date: 2026-08-22 13:26:58.420627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a046fe9654e8'
down_revision: Union[str, Sequence[str], None] = 'f3a4b5c6d7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seo_analysis_runs_project_id'), table_name='seo_analysis_runs')
    op.drop_table('seo_analysis_runs')
    op.drop_index(op.f('ix_parsed_page_facts_project_id'), table_name='parsed_page_facts')
    op.drop_table('parsed_page_facts')
    op.drop_index(op.f('ix_rule_evaluation_results_project_id'), table_name='rule_evaluation_results')
    op.drop_table('rule_evaluation_results')
    op.add_column('otps', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('refresh_tokens', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('token_blacklist', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('token_blacklist', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_blacklist', 'updated_at')
    op.drop_column('token_blacklist', 'created_at')
    op.drop_column('refresh_tokens', 'updated_at')
    op.drop_column('otps', 'updated_at')
    op.create_table('rule_evaluation_results',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('crawl_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rule_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('rule_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('score_impact', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rule_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('evaluated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('rule_evaluation_results_pkey'))
    )
    op.create_index(op.f('ix_rule_evaluation_results_project_id'), 'rule_evaluation_results', ['project_id'], unique=False)
    op.create_table('parsed_page_facts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('crawl_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('page_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('page_facts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('elements', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('parse_errors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('parsed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('parsed_page_facts_pkey'))
    )
    op.create_index(op.f('ix_parsed_page_facts_project_id'), 'parsed_page_facts', ['project_id'], unique=False)
    op.create_table('seo_analysis_runs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('crawl_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('overall_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('grade', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('total_pages_scored', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_rules_evaluated', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_passed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_failed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('critical_issues', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('warnings', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('error_pages', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('error_summary', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('category_scores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('top_issues', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('output_file_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('analysis_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('scored_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('seo_analysis_runs_pkey'))
    )
    op.create_index(op.f('ix_seo_analysis_runs_project_id'), 'seo_analysis_runs', ['project_id'], unique=True)
    # ### end Alembic commands ###
