"""crawler db models

Revision ID: b2393caacd1c
Revises: 6fc30c0ef671
Create Date: 2026-08-06 17:23:18.698389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2393caacd1c'
down_revision: Union[str, Sequence[str], None] = '6fc30c0ef671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='crawl_job_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_jobs_user_id'), 'crawl_jobs', ['user_id'], unique=False)
    op.create_table('crawl_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crawl_id', sa.UUID(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('max_pages', sa.Integer(), nullable=False),
    sa.Column('concurrency', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('delay_ms', sa.Integer(), nullable=False),
    sa.Column('follow_redirects', sa.Boolean(), nullable=False),
    sa.Column('respect_robots', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawl_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_configs_crawl_id'), 'crawl_configs', ['crawl_id'], unique=False)
    op.create_table('crawl_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crawl_id', sa.UUID(), nullable=False),
    sa.Column('parent_page_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.SmallInteger(), nullable=True),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('content_size', sa.BigInteger(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawl_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_page_id'], ['crawl_pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_pages_crawl_id'), 'crawl_pages', ['crawl_id'], unique=False)
    op.create_index(op.f('ix_crawl_pages_parent_page_id'), 'crawl_pages', ['parent_page_id'], unique=False)
    op.create_table('crawl_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crawl_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=True),
    sa.Column('error_type', sa.Enum('fetch_error', 'crawl_error', 'parse_error', 'timeout', 'connection_error', 'robots_error', name='crawl_error_type_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawl_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['crawl_pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_errors_crawl_id'), 'crawl_errors', ['crawl_id'], unique=False)
    op.create_index(op.f('ix_crawl_errors_page_id'), 'crawl_errors', ['page_id'], unique=False)
    op.create_table('page_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.Enum('image', 'css', 'javascript', 'font', 'video', 'pdf', 'favicon', name='asset_type_enum'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('status_code', sa.SmallInteger(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['crawl_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_assets_page_id'), 'page_assets', ['page_id'], unique=False)
    op.create_table('page_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('anchor_text', sa.Text(), nullable=True),
    sa.Column('rel', sa.String(length=100), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('is_nofollow', sa.Boolean(), nullable=False),
    sa.Column('link_type', sa.Enum('anchor', 'image', 'script', 'stylesheet', 'canonical', 'hreflang', name='link_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['crawl_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_links_page_id'), 'page_links', ['page_id'], unique=False)
    op.create_table('page_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('compressed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['crawl_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_snapshots_page_id'), 'page_snapshots', ['page_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_snapshots_page_id'), table_name='page_snapshots')
    op.drop_table('page_snapshots')
    op.drop_index(op.f('ix_page_links_page_id'), table_name='page_links')
    op.drop_table('page_links')
    op.drop_index(op.f('ix_page_assets_page_id'), table_name='page_assets')
    op.drop_table('page_assets')
    op.drop_index(op.f('ix_crawl_errors_page_id'), table_name='crawl_errors')
    op.drop_index(op.f('ix_crawl_errors_crawl_id'), table_name='crawl_errors')
    op.drop_table('crawl_errors')
    op.drop_index(op.f('ix_crawl_pages_parent_page_id'), table_name='crawl_pages')
    op.drop_index(op.f('ix_crawl_pages_crawl_id'), table_name='crawl_pages')
    op.drop_table('crawl_pages')
    op.drop_index(op.f('ix_crawl_configs_crawl_id'), table_name='crawl_configs')
    op.drop_table('crawl_configs')
    op.drop_index(op.f('ix_crawl_jobs_user_id'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    # ### end Alembic commands ###
