from typing import Any

RULE_GUIDANCE: dict[str, dict[str, Any]] = {
    "on_page_001": {
        "expected_value": "50–60 characters",
        "where_to_fix": "<head> → <title>",
        "how_to_fix": "Shorten the title while keeping the primary topic clear.",
        "example": "<title>SEO Audit Tool for Website Analysis</title>",
    },
    "on_page_002": {
        "expected_value": "140–160 characters",
        "where_to_fix": "<head> → <meta name='description'>",
        "how_to_fix": "Add a unique, relevant description summarizing the page content.",
        "example": '<meta name="description" content="Analyze your website SEO with our free audit tool.">',
    },
    "on_page_003": {
        "expected_value": "Exactly one H1 per page",
        "where_to_fix": "<body> → <h1>",
        "how_to_fix": "Keep one H1 that describes the page topic. Remove extra H1s.",
        "example": "<h1>Website SEO Audit Guide</h1>",
    },
    "on_page_004": {
        "expected_value": "Logical H1 → H2 → H3 hierarchy without skipped levels",
        "where_to_fix": "<body> → heading tags",
        "how_to_fix": "Organize headings in logical order. Do not skip levels.",
        "example": "<h1>Guide</h1>\n<h2>Chapter 1</h2>\n<h3>Section 1.1</h3>",
    },
    "on_page_006": {
        "expected_value": "Present and matches the preferred URL",
        "where_to_fix": "<head> → <link rel='canonical'>",
        "how_to_fix": "Add a canonical link to the preferred version of the page.",
        "example": "<link rel='canonical' href='https://example.com/page'>",
    },
    "on_page_007": {
        "expected_value": "Allows indexing unless intentionally restricted",
        "where_to_fix": "<head> → <meta name='robots'> or HTTP X-Robots-Tag header",
        "how_to_fix": "Review robots directives and ensure important pages are indexable.",
        "example": "<meta name='robots' content='index, follow'>",
    },
    "on_page_008": {
        "expected_value": "og:title, og:description, og:image, og:url present",
        "where_to_fix": "<head> → Open Graph meta tags",
        "how_to_fix": "Add complete Open Graph tags for social sharing.",
        "example": '<meta property="og:title" content="Page Title">\n<meta property="og:image" content="https://example.com/image.jpg">',
    },
    "technical_001": {
        "expected_value": "HTTPS enabled and all resources served securely",
        "where_to_fix": "Server configuration / CMS settings",
        "how_to_fix": "Install an SSL certificate and redirect HTTP to HTTPS.",
        "example": "Redirect HTTP → HTTPS at the server or load balancer.",
    },
    "technical_002": {
        "expected_value": "<meta name='viewport' content='width=device-width, initial-scale=1.0'>",
        "where_to_fix": "<head> → viewport meta tag",
        "how_to_fix": "Add the viewport meta tag for mobile rendering.",
        "example": "<meta name='viewport' content='width=device-width, initial-scale=1.0'>",
    },
    "technical_005": {
        "expected_value": "<!DOCTYPE html> at the start of the document",
        "where_to_fix": "Top of every HTML document",
        "how_to_fix": "Add <!DOCTYPE html> as the very first line.",
        "example": "<!DOCTYPE html>\n<html lang='en'>",
    },
    "technical_007": {
        "expected_value": "HSTS, X-Content-Type-Options, X-Frame-Options, Content-Security-Policy set",
        "where_to_fix": "HTTP response headers",
        "how_to_fix": "Configure security headers in your web server or application.",
        "example": "Strict-Transport-Security: max-age=31536000; includeSubDomains",
    },
    "technical_008": {
        "expected_value": "Valid robots.txt present and properly configured",
        "where_to_fix": "https://example.com/robots.txt",
        "how_to_fix": "Create or update robots.txt to allow or disallow crawlers as needed.",
        "example": "User-agent: *\nAllow: /\nDisallow: /admin/",
    },
    "technical_009": {
        "expected_value": "XML sitemap present and submitted to search engines",
        "where_to_fix": "https://example.com/sitemap.xml",
        "how_to_fix": "Generate an XML sitemap and submit it in Google Search Console.",
        "example": "<urlset xmlns='http://www.sitemaps.org/schemas/sitemap/0.9'>...</urlset>",
    },
    "technical_010": {
        "expected_value": "Schema.org JSON-LD markup for key page types",
        "where_to_fix": "<head> or <body> → <script type='application/ld+json'>",
        "how_to_fix": "Add JSON-LD structured data for Organization, Product, Article, etc.",
        "example": '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Organization","name":"Example"}</script>',
    },
    "missing_www_redirect": {
        "expected_value": "One canonical host with the other redirecting via 301",
        "where_to_fix": "Server / DNS / hosting provider configuration",
        "how_to_fix": "Choose www or non-www and set a permanent redirect.",
        "example": "Redirect https://example.com → https://www.example.com",
    },
    "links_003": {
        "expected_value": "All internal links return 2xx status codes",
        "where_to_fix": "HTML <a href> links throughout the site",
        "how_to_fix": "Fix or remove broken links. Update URLs if pages moved.",
        "example": "<a href='/new-page'>Link text</a>",
    },
    "links_004": {
        "expected_value": "Descriptive anchor text relevant to the destination",
        "where_to_fix": "HTML <a> anchor text",
        "how_to_fix": "Replace generic anchor text like 'click here' with descriptive text.",
        "example": "<a href='/seo-guide'>Read our SEO guide</a>",
    },
    "images_001": {
        "expected_value": "Every meaningful image has descriptive alt text",
        "where_to_fix": "<img alt='...'>",
        "how_to_fix": "Add concise alt text describing the image content or purpose.",
        "example": '<img src="/product.jpg" alt="Blue wireless headphones">',
    },
    "images_004": {
        "expected_value": "width and height attributes set on img tags",
        "where_to_fix": "<img width='...' height='...'>",
        "how_to_fix": "Add intrinsic dimensions to images to reduce layout shift.",
        "example": "<img src='/hero.jpg' width='1200' height='600' alt='Hero image'>",
    },
    "schema_001": {
        "expected_value": "Valid JSON-LD schema for relevant page types",
        "where_to_fix": "<head> or <body> → <script type='application/ld+json'>",
        "how_to_fix": "Add structured data for Organization, Product, Article, etc.",
        "example": '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Article","headline":"..."}</script>',
    },
    "perf_001": {
        "expected_value": "TTFB under 600ms",
        "where_to_fix": "Server / database / CDN configuration",
        "how_to_fix": "Optimize backend queries, enable caching, use a CDN.",
        "example": "Enable Redis cache for frequent DB queries.",
    },
    "perf_008": {
        "expected_value": "No client-side JavaScript errors",
        "where_to_fix": "Browser console / JavaScript source files",
        "how_to_fix": "Fix JavaScript errors reported in the browser console.",
        "example": "Check console for uncaught TypeError and fix source.",
    },
    "social_003": {
        "expected_value": "Links to social media profiles present",
        "where_to_fix": "Header, footer, or contact page",
        "how_to_fix": "Add links to your official social profiles.",
        "example": '<a href="https://twitter.com/example">Twitter</a>',
    },
    "social_005": {
        "expected_value": "og:image and twitter:image present and valid",
        "where_to_fix": "<head> → Open Graph / Twitter Card meta tags",
        "how_to_fix": "Add social image meta tags with a valid image URL.",
        "example": '<meta property="og:image" content="https://example.com/social.jpg">',
    },
    "security_002": {
        "expected_value": "No mixed content; all resources loaded over HTTPS",
        "where_to_fix": "HTML src/href attributes and CSS url() references",
        "how_to_fix": "Replace http:// URLs with https:// or protocol-relative URLs.",
        "example": "<img src='https://example.com/image.jpg'>",
    },
    "security_005": {
        "expected_value": "Strict-Transport-Security header with long max-age",
        "where_to_fix": "HTTP response headers",
        "how_to_fix": "Enable HSTS header with a long max-age.",
        "example": "Strict-Transport-Security: max-age=31536000; includeSubDomains",
    },
    "security_006": {
        "expected_value": "X-XSS-Protection and Content-Security-Policy headers set",
        "where_to_fix": "HTTP response headers",
        "how_to_fix": "Add XSS protection and CSP headers.",
        "example": "X-XSS-Protection: 1; mode=block",
    },
    "url_001": {
        "expected_value": "Lowercase, hyphen-separated, short, readable URLs",
        "where_to_fix": "URL path structure / CMS permalink settings",
        "how_to_fix": "Rewrite URLs to use hyphens and lowercase letters.",
        "example": "/seo-audit-tool",
    },
    "mobile_001": {
        "expected_value": "Viewport meta tag present",
        "where_to_fix": "<head> → <meta name='viewport'>",
        "how_to_fix": "Add the standard mobile viewport meta tag.",
        "example": "<meta name='viewport' content='width=device-width, initial-scale=1.0'>",
    },
    "http_status_001": {
        "expected_value": "200 for successful pages; proper redirects for moved pages",
        "where_to_fix": "Server configuration / redirect rules",
        "how_to_fix": "Fix status codes and redirect chains.",
        "example": "301 redirect old URL → new URL",
    },
    "hreflang_001": {
        "expected_value": "Correct hreflang annotations for all language/region variants",
        "where_to_fix": "<head> → <link rel='alternate' hreflang='...'>",
        "how_to_fix": "Add hreflang tags for each language or regional variant.",
        "example": "<link rel='alternate' hreflang='en-us' href='https://example.com/en-us/page'>",
    },
    "duplicate_001": {
        "expected_value": "Unique title tags across all pages",
        "where_to_fix": "<head> → <title>",
        "how_to_fix": "Make every page title unique and descriptive.",
        "example": "<title>Page-Specific Descriptive Title</title>",
    },
    "duplicate_002": {
        "expected_value": "Unique meta descriptions across all pages",
        "where_to_fix": "<head> → <meta name='description'>",
        "how_to_fix": "Write a unique meta description for each page.",
        "example": '<meta name="description" content="Page-specific description here.">',
    },
    "duplicate_003": {
        "expected_value": "Unique H1 tags across all pages",
        "where_to_fix": "<body> → <h1>",
        "how_to_fix": "Use a unique H1 on every page.",
        "example": "<h1>Page-Specific Heading</h1>",
    },
    "content_001": {
        "expected_value": "Substantial, useful content (typically 300+ words)",
        "where_to_fix": "Main page content area",
        "how_to_fix": "Expand thin pages with original, useful content.",
        "example": "Add paragraphs, lists, and media relevant to the topic.",
    },
    "content_006": {
        "expected_value": "Unique content or canonicalized duplicates",
        "where_to_fix": "Page content or canonical tags",
        "how_to_fix": "Rewrite duplicate content or use rel=canonical.",
        "example": "<link rel='canonical' href='https://example.com/original-page'>",
    },
    "images_002": {
        "expected_value": "Optimized image file sizes",
        "where_to_fix": "Image files / CMS media library",
        "how_to_fix": "Compress images and use modern formats like WebP.",
        "example": "Convert PNG to WebP and enable compression.",
    },
    "images_003": {
        "expected_value": "Lazy loading enabled for below-the-fold images",
        "where_to_fix": "<img loading='lazy'>",
        "how_to_fix": "Add loading='lazy' to images below the fold.",
        "example": '<img src="/photo.jpg" loading="lazy" alt="...">',
    },
    "images_005": {
        "expected_value": "srcset and sizes attributes for responsive images",
        "where_to_fix": "<img srcset='...' sizes='...'>",
        "how_to_fix": "Provide multiple image sizes for different viewports.",
        "example": "<img srcset='small.jpg 480w, large.jpg 1024w' sizes='(max-width: 600px) 480px, 1024px' alt='...'>",
    },
    "images_006": {
        "expected_value": "Modern formats like WebP/AVIF used where supported",
        "where_to_fix": "Image files / CMS media library / <picture> element",
        "how_to_fix": "Serve WebP or AVIF with fallbacks.",
        "example": "<picture><source srcset='image.webp' type='image/webp'><img src='image.jpg' alt='...'></picture>",
    },
    "schema_002": {
        "expected_value": "Organization or Person schema present",
        "where_to_fix": "<head> or <body> → JSON-LD",
        "how_to_fix": "Add Organization schema with name, logo, and sameAs links.",
        "example": '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Organization","name":"Example"}</script>',
    },
    "schema_003": {
        "expected_value": "BreadcrumbList schema present on breadcrumb pages",
        "where_to_fix": "<head> or <body> → JSON-LD",
        "how_to_fix": "Add BreadcrumbList structured data.",
        "example": '<script type="application/ld+json">{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[...]}</script>',
    },
    "schema_004": {
        "expected_value": "Product schema for product pages",
        "where_to_fix": "<head> or <body> → JSON-LD",
        "how_to_fix": "Add Product schema with name, price, availability, etc.",
        "example": '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Product","name":"Product"}</script>',
    },
    "schema_005": {
        "expected_value": "Article schema for blog/news pages",
        "where_to_fix": "<head> or <body> → JSON-LD",
        "how_to_fix": "Add Article schema with headline, author, datePublished.",
        "example": '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Article","headline":"..."}</script>',
    },
    "schema_006": {
        "expected_value": "FAQPage schema when FAQ content is present",
        "where_to_fix": "<head> or <body> → JSON-LD",
        "how_to_fix": "Add FAQPage schema for question/answer content.",
        "example": '<script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[...]}</script>',
    },
    "social_004": {
        "expected_value": "Social profile links present and valid",
        "where_to_fix": "Header, footer, or contact page",
        "how_to_fix": "Add links to official social profiles.",
        "example": '<a href="https://linkedin.com/company/example">LinkedIn</a>',
    },
    "security_001": {
        "expected_value": "Valid SSL/TLS certificate with correct domain coverage",
        "where_to_fix": "Server / hosting SSL configuration",
        "how_to_fix": "Install or renew SSL certificate.",
        "example": "Use Let's Encrypt or cloud provider certificate.",
    },
    "security_003": {
        "expected_value": "No mixed content warnings",
        "where_to_fix": "HTML src/href and CSS url() references",
        "how_to_fix": "Replace http:// URLs with https://.",
        "example": "<img src='https://example.com/image.jpg'>",
    },
    "security_004": {
        "expected_value": "X-Frame-Options set to DENY or SAMEORIGIN",
        "where_to_fix": "HTTP response headers",
        "how_to_fix": "Add X-Frame-Options header.",
        "example": "X-Frame-Options: SAMEORIGIN",
    },
    "a11y_001": {
        "expected_value": "All images have meaningful alt text",
        "where_to_fix": "<img alt='...'>",
        "how_to_fix": "Add descriptive alt text to every meaningful image.",
        "example": '<img src="/diagram.jpg" alt="Workflow diagram showing 3 steps">',
    },
    "a11y_002": {
        "expected_value": "All form inputs have associated labels",
        "where_to_fix": "<label for='...'> or aria-label",
        "how_to_fix": "Add labels to form controls.",
        "example": "<label for='email'>Email</label>\n<input id='email' type='email'>",
    },
    "a11y_003": {
        "expected_value": "Logical heading structure with a single H1",
        "where_to_fix": "<body> → heading tags",
        "how_to_fix": "Organize headings in a logical hierarchy.",
        "example": "<h1>Guide</h1>\n<h2>Chapter 1</h2>\n<h3>Section</h3>",
    },
    "a11y_004": {
        "expected_value": "Sufficient color contrast for text",
        "where_to_fix": "CSS color values",
        "how_to_fix": "Increase contrast to meet WCAG AA.",
        "example": "color: #1a1a1a; background-color: #ffffff;",
    },
    "a11y_005": {
        "expected_value": "All interactive elements are keyboard accessible",
        "where_to_fix": "HTML interactive elements / event handlers",
        "how_to_fix": "Use native buttons/links or add keyboard handlers.",
        "example": "<button onclick='submit()'>Submit</button>",
    },
    "a11y_006": {
        "expected_value": "Skip navigation links present",
        "where_to_fix": "Top of page <body>",
        "how_to_fix": "Add a skip-to-content link.",
        "example": '<a href="#main">Skip to content</a>',
    },
    "a11y_007": {
        "expected_value": "Language attribute set on <html>",
        "where_to_fix": "<html lang='...'>",
        "how_to_fix": "Set the lang attribute on the html element.",
        "example": "<html lang='en'>",
    },
    "a11y_008": {
        "expected_value": "Form inputs have accessible names",
        "where_to_fix": "<input aria-label='...'> or <label>",
        "how_to_fix": "Add labels or aria-labels to inputs.",
        "example": "<input type='search' aria-label='Search'>",
    },
    "perf_002": {
        "expected_value": "Server response time under 600ms",
        "where_to_fix": "Server / database / CDN configuration",
        "how_to_fix": "Optimize backend queries, enable caching, use a CDN.",
        "example": "Enable Redis cache for frequent queries.",
    },
    "perf_003": {
        "expected_value": "No render-blocking CSS or JS in <head>",
        "where_to_fix": "<head> → <link rel='stylesheet'> / <script>",
        "how_to_fix": "Defer non-critical CSS and JS.",
        "example": '<link rel="preload" href="style.css" as="style" onload="this.onload=null;this.rel=\'stylesheet\'">',
    },
    "perf_004": {
        "expected_value": "Images optimized and appropriately sized",
        "where_to_fix": "Image files / <img> attributes",
        "how_to_fix": "Compress images and use modern formats.",
        "example": "<img src='image.webp' width='800' height='600' alt='...'>",
    },
    "perf_005": {
        "expected_value": "Static assets cached with long TTL",
        "where_to_fix": "HTTP Cache-Control headers",
        "how_to_fix": "Set Cache-Control headers for static assets.",
        "example": "Cache-Control: public, max-age=31536000",
    },
    "perf_006": {
        "expected_value": "Text compression enabled (gzip/brotli)",
        "where_to_fix": "Server compression settings",
        "how_to_fix": "Enable gzip or brotli compression.",
        "example": "Content-Encoding: gzip",
    },
    "perf_007": {
        "expected_value": "Total page size under 2 MB",
        "where_to_fix": "Page assets / media / scripts",
        "how_to_fix": "Reduce asset sizes and remove unused resources.",
        "example": "Compress images and minify CSS/JS.",
    },
}
